/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'error-container': '#ffdad6',
        'surface-dim': '#dcdad4',
        'tertiary-fixed': '#d5e6de',
        'outline-variant': '#c0c8c4',
        'tertiary-container': '#33423c',
        'on-tertiary-fixed-variant': '#3b4a44',
        'surface-container': '#f0eee8',
        background: '#fbf9f3',
        'on-surface-variant': '#404945',
        'on-tertiary-container': '#9daea6',
        'secondary-fixed': '#ffddb0',
        tertiary: '#1d2c27',
        'on-error-container': '#93000a',
        'surface-tint': '#396759',
        'secondary-container': '#febe58',
        'inverse-on-surface': '#f3f1eb',
        'surface-variant': '#e4e2dd',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#30312d',
        ink: '#14231C',
        deep: '#17473A',
        ochre: '#B07A17',
        slate: '#6B7B74',
        rule: '#D9D4C7',
        'on-primary-fixed-variant': '#204f41',
        'surface-container-high': '#eae8e2',
        'on-background': '#1b1c18',
        'on-primary-container': '#85b5a4',
        secondary: '#805600',
        error: '#ba1a1a',
        'primary-fixed-dim': '#a0d1bf',
        'on-secondary-fixed': '#291800',
        'inverse-primary': '#a0d1bf',
        'on-surface': '#1b1c18',
        'on-tertiary-fixed': '#101e19',
        outline: '#717975',
        'on-secondary': '#ffffff',
        'surface-bright': '#fbf9f3',
        'primary-fixed': '#bbeddb',
        'on-primary-fixed': '#002018',
        primary: '#003025',
        'surface-container-highest': '#e4e2dd',
        'primary-container': '#17473a',
        'tertiary-fixed-dim': '#b9cac2',
        'on-primary': '#ffffff',
        'on-secondary-fixed-variant': '#614000',
        'on-error': '#ffffff',
        'surface-container-low': '#f5f3ed',
        'secondary-fixed-dim': '#fbbb56',
        surface: '#fbf9f3',
        'on-secondary-container': '#734d00',
        'on-tertiary': '#ffffff',
        sage: '#EAF3EE',
        'console-bg': '#0E0E0E',
        'console-panel': '#1A1A1A',
        'console-border': '#333333',
        'console-muted': '#888888',
        'console-dim': '#555555',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '24px',
        base: '4px',
        'stack-loose': '32px',
        'stack-dense': '16px',
        'stack-compact': '8px',
        'margin-page': '40px',
        'stack-xs': '4px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'stack-xl': '64px',
        'container-max': '1140px',
        margin: '48px',
        unit: '4px',
      },
      maxWidth: {
        'container-max': '1140px',
      },
      fontFamily: {
        footnote: ['Public Sans', 'system-ui', 'sans-serif'],
        'section-kicker': ['Public Sans', 'system-ui', 'sans-serif'],
        subtitle: ['Public Sans', 'system-ui', 'sans-serif'],
        'page-title': ['Newsreader', 'Georgia', 'serif'],
        'table-header': ['Public Sans', 'system-ui', 'sans-serif'],
        body: ['Public Sans', 'system-ui', 'sans-serif'],
        'panel-header': ['Newsreader', 'Georgia', 'serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
        'body-lg': ['Public Sans', 'system-ui', 'sans-serif'],
        'body-md': ['Public Sans', 'system-ui', 'sans-serif'],
        'data-md': ['JetBrains Mono', 'ui-monospace', 'monospace'],
        'data-lg': ['JetBrains Mono', 'ui-monospace', 'monospace'],
        citation: ['JetBrains Mono', 'ui-monospace', 'monospace'],
        'headline-sm': ['Newsreader', 'Georgia', 'serif'],
        'headline-md': ['Newsreader', 'Georgia', 'serif'],
        'display-lg': ['Newsreader', 'Georgia', 'serif'],
        'label-caps': ['Public Sans', 'system-ui', 'sans-serif'],
        display: ['Newsreader', 'Georgia', 'serif'],
      },
      fontSize: {
        footnote: ['9px', { lineHeight: '1.4', fontWeight: '400' }],
        'section-kicker': [
          '13px',
          { lineHeight: '1.4', letterSpacing: '0.1em', fontWeight: '700' },
        ],
        subtitle: ['15px', { lineHeight: '1.5', fontWeight: '400' }],
        'page-title': [
          '34px',
          { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'table-header': ['10px', { lineHeight: '1.2', fontWeight: '700' }],
        body: ['13px', { lineHeight: '1.6', fontWeight: '400' }],
        'panel-header': ['18px', { lineHeight: '1.3', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '1.5', fontWeight: '400' }],
        'data-md': ['14px', { lineHeight: '1.4', fontWeight: '400' }],
        'data-lg': ['24px', { lineHeight: '1', fontWeight: '500' }],
        citation: ['10px', { lineHeight: '1', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '1.4', fontWeight: '500' }],
        'headline-md': ['26px', { lineHeight: '1.3', fontWeight: '500' }],
        'display-lg': ['48px', { lineHeight: '1.2', fontWeight: '400' }],
        'label-caps': [
          '11px',
          { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '700' },
        ],
      },
      keyframes: {
        'pulse-glow': {
          '0%': { boxShadow: '0 0 0 0 rgba(0, 48, 37, 0.4)' },
          '70%': { boxShadow: '0 0 0 6px rgba(0, 48, 37, 0)' },
          '100%': { boxShadow: '0 0 0 0 rgba(0, 48, 37, 0)' },
        },
        'pulse-ring': {
          '0%': { transform: 'scale(0.8)', opacity: '0.5' },
          '100%': { transform: 'scale(1.5)', opacity: '0' },
        },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(6px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'pulse-glow': 'pulse-glow 2s infinite',
        'fade-in-up': 'fade-in-up 240ms ease-out both',
      },
    },
  },
  plugins: [],
}
