/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed': '#85fab0',
        'on-tertiary-container': '#b3ffca',
        'primary-container': '#197a56',
        primary: '#006041',
        'on-error-container': '#93000a',
        outline: '#6f7a72',
        'error-container': '#ffdad6',
        'on-secondary-container': '#007238',
        'on-tertiary-fixed': '#00210f',
        'primary-fixed': '#9bf5c8',
        'on-primary-fixed-variant': '#005237',
        'tertiary-fixed-dim': '#68dd96',
        'on-secondary-fixed': '#00210c',
        'on-tertiary-fixed-variant': '#00522d',
        'surface-container-high': '#eae7e7',
        'on-secondary': '#ffffff',
        'secondary-fixed-dim': '#29e37a',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#007c47',
        'on-primary': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'secondary-container': '#50fd91',
        'surface-container': '#f0eded',
        'surface-variant': '#e4e2e1',
        background: '#fcf9f8',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'surface-bright': '#fcf9f8',
        'inverse-primary': '#80d8ad',
        'surface-dim': '#dcd9d9',
        tertiary: '#006136',
        surface: '#fcf9f8',
        'on-surface-variant': '#3f4943',
        'on-primary-fixed': '#002114',
        'on-primary-container': '#acffd4',
        'surface-tint': '#006c4a',
        'on-secondary-fixed-variant': '#005227',
        error: '#ba1a1a',
        'inverse-on-surface': '#f3f0f0',
        'on-background': '#1b1c1c',
        'surface-container-highest': '#e4e2e1',
        'outline-variant': '#bec9c1',
        'inverse-surface': '#303030',
        'primary-fixed-dim': '#80d8ad',
        'secondary-fixed': '#61ff97',
        secondary: '#006d35',
        'on-surface': '#1b1c1c',
        sage: '#EAF3EE',
        'console-bg': '#0E0E0E',
        'console-panel': '#1A1A1A',
        'console-border': '#333333',
        'console-muted': '#888888',
        'console-dim': '#555555',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-xs': '4px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'stack-xl': '64px',
        'container-max': '1140px',
        gutter: '24px',
        margin: '48px',
        unit: '4px',
      },
      maxWidth: {
        'container-max': '1140px',
      },
      fontFamily: {
        footnote: ['Inter', 'system-ui', 'sans-serif'],
        'section-kicker': ['Inter', 'system-ui', 'sans-serif'],
        subtitle: ['Inter', 'system-ui', 'sans-serif'],
        'page-title': ['Inter', 'system-ui', 'sans-serif'],
        'table-header': ['Inter', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        'panel-header': ['Inter', 'system-ui', 'sans-serif'],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      fontSize: {
        footnote: ['9px', { lineHeight: '1.4', fontWeight: '400' }],
        'section-kicker': [
          '13px',
          { lineHeight: '1.4', letterSpacing: '0.1em', fontWeight: '700' },
        ],
        subtitle: ['15px', { lineHeight: '1.5', fontWeight: '400' }],
        'page-title': [
          '34px',
          { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'table-header': ['10px', { lineHeight: '1.2', fontWeight: '700' }],
        body: ['13px', { lineHeight: '1.6', fontWeight: '400' }],
        'panel-header': ['18px', { lineHeight: '1.3', fontWeight: '700' }],
      },
      keyframes: {
        'pulse-glow': {
          '0%': { boxShadow: '0 0 0 0 rgba(0, 96, 65, 0.4)' },
          '70%': { boxShadow: '0 0 0 6px rgba(0, 96, 65, 0)' },
          '100%': { boxShadow: '0 0 0 0 rgba(0, 96, 65, 0)' },
        },
        'pulse-ring': {
          '0%': { transform: 'scale(0.8)', opacity: '0.5' },
          '100%': { transform: 'scale(1.5)', opacity: '0' },
        },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(6px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'pulse-glow': 'pulse-glow 2s infinite',
        'fade-in-up': 'fade-in-up 240ms ease-out both',
      },
    },
  },
  plugins: [],
}
